sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id:
    access-key-secret:
    bucket-name: b-sp
    endpoint: oss-cn-beijing.aliyuncs.com
  qiniu:
    access-key-id: V9WfNybiDaXSZaeAgi4kCnST8mjX8k0SuvUFLKnG
    access-key-secret: fA_5dj41mLKLSDwNC1qq3xu1--KU_yCXEKGLB8Yv
    bucket-name: bldxj
    img-url: pic.icefun.icu
